//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finary.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public long xID { get; set; }
        public long xUserID { get; set; }
        public System.DateTime xDate { get; set; }
        public string xIP { get; set; }
        public string xDeviceID { get; set; }
        public string xUserAgent { get; set; }
        public bool xFraudDetected { get; set; }
        public string xRayID { get; set; }
    
        public virtual User User { get; set; }
    }
}
