//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finary.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateMessage
    {
        public long xID { get; set; }
        public long xUserID { get; set; }
        public string xTitle { get; set; }
        public string xMessage { get; set; }
        public Nullable<System.DateTime> xUserReadDate { get; set; }
        public System.DateTime xSendDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
