//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finary.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefferalWithdrawal
    {
        public long xID { get; set; }
        public long xUserID { get; set; }
        public string xCurrency { get; set; }
        public byte xStatus { get; set; }
        public string xWalletAddress { get; set; }
        public string xDescription { get; set; }
        public System.DateTime xDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
