//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finary.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefferalShareHistory
    {
        public long xID { get; set; }
        public long xUserID { get; set; }
        public long xFromUserID { get; set; }
        public string xFromCurrency { get; set; }
        public double xValue { get; set; }
        public System.DateTime xDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
