//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finary.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Exchange = new HashSet<Exchange>();
            this.LoginHistory = new HashSet<LoginHistory>();
            this.PrivateMessage = new HashSet<PrivateMessage>();
            this.RefferalShareHistory = new HashSet<RefferalShareHistory>();
            this.RefferalShareHistory1 = new HashSet<RefferalShareHistory>();
            this.RefferalWallet = new HashSet<RefferalWallet>();
            this.RefferalWithdrawal = new HashSet<RefferalWithdrawal>();
            this.RialTransaction = new HashSet<RialTransaction>();
            this.UserBankAccount = new HashSet<UserBankAccount>();
            this.User1 = new HashSet<User>();
            this.Withdrawal = new HashSet<Withdrawal>();
        }
    
        public long xID { get; set; }
        public string xFullName { get; set; }
        public string xEmail { get; set; }
        public string xCellphone { get; set; }
        public string xTel { get; set; }
        public string xPassword { get; set; }
        public string xSalt { get; set; }
        public bool xIsActive { get; set; }
        public string xDescription { get; set; }
        public Nullable<long> xNationalIDImage { get; set; }
        public string xNationalIDNumber { get; set; }
        public bool xIsEmailValidated { get; set; }
        public bool xIsNationalIDValidated { get; set; }
        public bool xTelValidated { get; set; }
        public bool xCellphoneValidated { get; set; }
        public System.DateTime xSignupDate { get; set; }
        public Nullable<System.DateTime> xLastSigninDate { get; set; }
        public string xActivationCode { get; set; }
        public Nullable<System.DateTime> xActivationCodeExpireAt { get; set; }
        public string xCellphoneActivationCode { get; set; }
        public Nullable<System.DateTime> xLastSendEmailDate { get; set; }
        public Nullable<System.DateTime> xLastSendSmsDate { get; set; }
        public long xRialWallet { get; set; }
        public double xTetherWallet { get; set; }
        public long xInviteID { get; set; }
        public long xRefferalSharePercent { get; set; }
        public Nullable<long> xInviter { get; set; }
        public long xMaxDailyRialAmount { get; set; }
        public long xTodayRialAmount { get; set; }
        public byte xSubscriptionType { get; set; }
        public System.DateTime xSubscriptionExpireDate { get; set; }
        public byte xUserValidationProgress { get; set; }
        public long xTotalInvitedUsers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exchange> Exchange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginHistory> LoginHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrivateMessage> PrivateMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefferalShareHistory> RefferalShareHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefferalShareHistory> RefferalShareHistory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefferalWallet> RefferalWallet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefferalWithdrawal> RefferalWithdrawal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RialTransaction> RialTransaction { get; set; }
        public virtual SystemFile SystemFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBankAccount> UserBankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Withdrawal> Withdrawal { get; set; }
    }
}
